### ISSUE TITLE
Username invalid error

### ISSUE THREAD

**Issue by blisaham** [flagrow/telegram#3]
below is the screenshot 

http://blisaham.com/assets/files/2018-10-02/1538443588-142456-error.png

 my botname is blisahambot, inserted the name and token to setting field. and linked my bot to my domain. but when i tri to login, i get that error. 

please help. thank you very much

**Comment by clarkwinkelmann** [comment]
Thanks for the report.

I'm not too sure where that error could come from. It could be from Telegram and not from this extension. Could you check your bot is correctly enabled and that you copied the bot username and token exactly as they are (with correct lower/upper case and no spaces before or after) ?

**Comment by blisaham** [comment]
already enable the bot, ctrl + C and ctrl V the name and token, will try to make a new bot. will report soon

**Comment by blisaham** [comment]
turn out i miss spell the domain name, **but after click the accept button, i redirect back to sign up form. not logged.** 
![tele login 3](https://user-images.githubusercontent.com/43768236/46389962-7368ac80-c6ff-11e8-962a-ca5d805e326a.png)

![tele login 4](https://user-images.githubusercontent.com/43768236/46389960-6f3c8f00-c6ff-11e8-80ef-89a87aa3bebe.png)


please help.

**Comment by clarkwinkelmann** [comment]
That's actually intended. You can see that the username field is greyed out because it's your Telegram username. You still need to fill in an email address (but you won't be asked to confirm it) and accept any other field added by other extensions (here I notice the Terms extension).

The exact same thing happen if you use other social login providers. Except email is already filled in for those.

Just fill the remaining fields and your account will be created and linked to the Telegram account.

Let me know if you need further help :wink:

**Comment by clarkwinkelmann** [comment]
Also quick note, I strongly suggest you force access to your forum via HTTPS only (and update the url in config.php accordingly). You even already have a valid SSL certificate.

**Comment by blisaham** [comment]
ah.. i miss understood,  okay.. thank you very much, great extension. 

(will force to https, thank for the sugesstion)
